#!/bin/sh
# init temporary image location
image_loc="/tmp/$(date | sed 's/ /_/g').png"
# screenshot reMarkable tablet and save image
reSnap -s $REMARKABLE_IP -n -o $image_loc > /dev/null 2> /dev/null
# upload image to s3
aws s3api put-object --bucket zettelimages --key $(basename $image_loc) --body $image_loc --content-type="image/png" > /dev/null
# echo link to the s3 object
echo "![image](https://s3.us-west-1.amazonaws.com/zettelimages/$(basename $image_loc))"
