#!/bin/bash

## USAGE: echo ":smiley:" | toemoji
declare -A emoji

emoji[gorilla]=🦍
emoji[flowers]=💐
emoji[dolphin]=🐬
emoji[joystick]=🕹
emoji[smiley]=😃

toemoji() {
  while read -r line; do
    for k in ${!emoji[@]}; do
      line=${line//:$k:/${emoji[$k]}} 
    done
    echo "$line"
  done
}

toemoji "$@"
