#!/bin/bash

declare -A emoji

emoji[gorilla]=🦍
emoji[flowers]=💐
emoji[dolphin]=🐬
emoji[joystick]=🕹

toemoji() {
  while read -r line; do
    for k in ${emoji[@]}; do
      line=${line//:$k:/${emoji[$k]}} 
    done
    echo "$line"
  done
}

toemoji "$@"
